"""Add anomaly_count to documents

Revision ID: 7944cf3e216b
Revises: fa91d445cba2
Create Date: 2025-11-01 06:43:42.357353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7944cf3e216b'
down_revision: Union[str, None] = 'fa91d445cba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('anomaly_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'anomaly_count')
    # ### end Alembic commands ###
